### ISSUE TITLE
v5.2.3: Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by priyeshshah11** [react-native-cameraroll/react-native-cameraroll#471]
We are upgrading to react-native v0.71.2 & during that upgrade we also upgraded react-native-cameraroll from v4.1.2 to v5.2.3. Thus we changed our import to `import {CameraRoll} from '@react-native-camera-roll/camera-roll';` 

Now, our [jest tests](https://github.com/Expensify/App/actions/runs/4304233452/jobs/7504973715) have started failing with this error. Please refer to the stack below.
`Invariant Violation: new NativeEventEmitter() requires a non-null argument.`

All our test does is just renders the App which has the CameraRoll import. 

```
 Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

      1 | import RNFetchBlob from 'react-native-blob-util';
    > 2 | import {CameraRoll} from '@react-native-camera-roll/camera-roll';
        | ^
      3 | import lodashGet from 'lodash/get';
      4 | import * as FileUtils from './FileUtils';
      5 | import CONST from '../../CONST';

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:46:16)
      at Object.<anonymous> (node_modules/@react-native-camera-roll/camera-roll/lib/commonjs/CameraRollIOSPermission.ts:21:39)
      at Object.<anonymous> (node_modules/@react-native-camera-roll/camera-roll/lib/commonjs/index.ts:3:1)
      at Object.<anonymous> (src/libs/fileDownload/index.ios.js:2:1)
      at Object.<anonymous> (src/pages/home/report/ContextMenu/ContextMenuActions.js:14:1)
      at Object.<anonymous> (src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js:12:1)
      at Object.<anonymous> (src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js:10:1)
      at Object.<anonymous> (src/Expensify.js:28:1)
      at Object.<anonymous> (src/App.js:10:1)
      at Object.<anonymous> (tests/ui/UnreadIndicatorsTest.js:9:1)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)


Test Suites: 2 failed, 35 passed, 37 total
```

**Comment by Gijuno** [comment]
Same here. Are there any solutions? 
I'm just trying to fix `RNCCameraRollPermissionModule` for nativeEventEmitter

**Comment by Gijuno** [comment]
I solved it. You can use this codes with patch-packages.

Start on `line: 10` at `node_modules/@react-native-camera-roll/camera-roll/lib/commonjs/CameraRollIOSPermission.js`
``` diff
var _cameraRollPermissionNativeInterface = _interopRequireDefault(require("./cameraRollPermissionNativeInterface"));
 
-function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
+function _interopRequireDefault(obj) {
+  return obj && obj.__esModule ? obj : {
+    "default": obj
+  };
+}
 
 const isIOS = _reactNative.Platform.OS === 'ios';
 
-if (isIOS && _cameraRollPermissionNativeInterface.default == null) {
-  console.error("photoLibraryPermissionModule: Native Module 'photoLibraryPermissionModule' was null! Did you run pod install?");
+var nativeModule;
+if (isIOS) {
+  nativeModule = _cameraRollPermissionNativeInterface
 }
 
-const cameraRollEventEmitter = new _reactNative.NativeEventEmitter(isIOS ? _cameraRollPermissionNativeInterface.default : undefined);
+const cameraRollEventEmitter = new _reactNative.NativeEventEmitter(nativeModule);
 exports.cameraRollEventEmitter = cameraRollEventEmitter;
 
 const iosReadGalleryPermission = accessLevel => {
```

I Hope you solve it with these codes 🙏

**Comment by Arjan-Zuidema** [comment]
@Gijuno Maybe you can create a fix and make a pull request. I can then look at it and we can fix the issue

**Comment by TomJerry56** [comment]
Mocking the NativeEventEmitter, fixed the issue for me - jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter');

**Comment by TomJerry56** [comment]
I'm facing  the error- Cannot read properties of undefined (reading 'RNCCameraRoll') where I use save from camera-roll in jest

**Comment by TomJerry56** [comment]
I'm facing the error- Cannot read properties of undefined (reading 'RNCCameraRoll') where I use save from camera-roll in jest.
Any fix for this?

**Comment by Arjan-Zuidema** [comment]
Does this still occur on the latest version?

**Comment by TomJerry56** [comment]
Getting same error with react-native-clipboard/clipboard also.

**Comment by TomJerry56** [comment]
> Does this still occur on the latest version?

yes using 5.0.4

**Comment by Arjan-Zuidema** [comment]
Latest version is 5.7.2
