### ISSUE TITLE
Fail when snap shot test

### ISSUE THREAD

**Issue by NickLinkSports** [react-native-cameraroll/react-native-cameraroll#527]
I get the error below during the snapshot test. I installed it as per the manual and re-installed node_modules.
Please help me.

```
 ● Test suite failed to run

    Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCCameraRoll' could not be found. Verify that a module by this name is registered in the native binary.

 at invariant (node_modules/invariant/invariant.js:40:15)
      at Object.getEnforcing (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:41:3)
      at Object.<anonymous> (node_modules/@react-native-camera-roll/camera-roll/lib/commonjs/NativeCameraRollModule.ts:62:36)
      at Object.<anonymous> (node_modules/@react-native-camera-roll/camera-roll/lib/commonjs/CameraRoll.ts:8:1)
```

react-native-cameraroll : 5.6.0
React Native : 0.66.5
OS : Mac M1

**Comment by NickLinkSports** [comment]
I find it.
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/496
